version: "3.5"

services:
  server:
    build: server
    env_file: ./server/.env
    environment:
      NODE_ENV: production
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mme
  cms:
    build: cms
  client:
    build: client
    depends_on:
      - cms
      - server
